"""Setup cascades 4

Revision ID: 2cd374733460
Revises: 385a987b718b
Create Date: 2025-10-15 12:23:35.062266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '2cd374733460'
down_revision: Union[str, None] = '385a987b718b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userlikehistory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('userlikehistory_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('userplayhistory', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('userplayhistory_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplayhistory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userplayhistory_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    with op.batch_alter_table('userlikehistory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('userlikehistory_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    # ### end Alembic commands ###
