"""Track current position

Revision ID: 32a396471ba6
Revises: e25a9f873903
Create Date: 2025-10-05 00:18:23.426943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '32a396471ba6'
down_revision: Union[str, None] = 'e25a9f873903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplayhistory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_known_position', sa.Float(), server_default='0.0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplayhistory', schema=None) as batch_op:
        batch_op.drop_column('last_known_position')

    # ### end Alembic commands ###
