"""Setup cascades 3

Revision ID: 385a987b718b
Revises: 893eec63d1a7
Create Date: 2025-10-15 12:12:55.311133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '385a987b718b'
down_revision: Union[str, None] = '893eec63d1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastrecommendation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcastrecommendation_user_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('podcastrecommendation_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'userprofile', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastrecommendation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcastrecommendation_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('podcastrecommendation_user_id_fkey'), 'userprofile', ['user_id'], ['id'])

    # ### end Alembic commands ###
