"""Setup cascades

Revision ID: 61eef3d0b6a8
Revises: 32a396471ba6
Create Date: 2025-10-15 12:05:10.602449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '61eef3d0b6a8'
down_revision: Union[str, None] = '32a396471ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcast_profile_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'userprofile', ['profile_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('podcastauthorpodcast', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcastauthorpodcast_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcastgenerationtask_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcastgenerationtask_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    with op.batch_alter_table('podcastauthorpodcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcastauthorpodcast_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcast_profile_id_fkey'), 'userprofile', ['profile_id'], ['id'])

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    # ### end Alembic commands ###
