"""Complete basic live generation

Revision ID: 6291b757feff
Revises: ac94e670aabd
Create Date: 2025-10-16 06:35:17.332596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6291b757feff'
down_revision: Union[str, None] = 'ac94e670aabd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastauthorpersona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('podcastquestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'userprofile', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastquestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('podcastauthorpersona', schema=None) as batch_op:
        batch_op.drop_column('voice')

    # ### end Alembic commands ###
