"""add progress message

Revision ID: 6befde9ade9f
Revises: 50ed2c793a38
Create Date: 2025-06-16 13:49:40.335589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6befde9ade9f'
down_revision: Union[str, None] = '50ed2c793a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.drop_column('progress_message')

    # ### end Alembic commands ###
