"""Setup cascades 2

Revision ID: 893eec63d1a7
Revises: 61eef3d0b6a8
Create Date: 2025-10-15 12:09:54.783159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '893eec63d1a7'
down_revision: Union[str, None] = '61eef3d0b6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcastepisode_podcast_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcastepisode_podcast_id_fkey'), 'podcast', ['podcast_id'], ['id'])

    # ### end Alembic commands ###
