"""Implement subscriptions

Revision ID: 94ffa5036ae5
Revises: 6291b757feff
Create Date: 2025-10-16 09:31:16.420427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '94ffa5036ae5'
down_revision: Union[str, None] = '6291b757feff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotausage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quota_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('carryover', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quota_id'], ['quota.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usersubscription',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptionplan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quotaplanoverride', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quota_id', sa.Uuid(), nullable=False))
        batch_op.create_foreign_key(None, 'quota', ['quota_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('subscriptionplan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptionplan', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('quotaplanoverride', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quota_id')

    op.drop_table('usersubscription')
    op.drop_table('quotausage')
    # ### end Alembic commands ###
