"""Add generation data to the PodcastGenTask

Revision ID: a3459514aba5
Revises: 9a8d6faa23ec
Create Date: 2025-06-24 11:48:00.769020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a3459514aba5'
down_revision: Union[str, None] = '9a8d6faa23ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.drop_column('generation_data')

    # ### end Alembic commands ###
