"""Implement basic live generation 2

Revision ID: ac94e670aabd
Revises: b91cc87f087a
Create Date: 2025-10-16 01:07:17.369711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ac94e670aabd'
down_revision: Union[str, None] = 'b91cc87f087a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastquestion', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'podcastauthorpersona', ['persona_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastquestion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
