"""Add gender and country to Persona

Revision ID: c56ab9869c9a
Revises: 6858090487dc
Create Date: 2025-06-16 15:32:03.836538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c56ab9869c9a'
down_revision: Union[str, None] = '6858090487dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastauthorpersona', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.add_column(sa.Column('podcast_id', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(None, 'podcast', ['podcast_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastgenerationtask', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('podcast_id')

    with op.batch_alter_table('podcastauthorpersona', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
