"""Setup cascades 5

Revision ID: ce86322b1c93
Revises: 2cd374733460
Create Date: 2025-10-15 12:33:12.228064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ce86322b1c93'
down_revision: Union[str, None] = '2cd374733460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('conversation_episode_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcastepisode', ['episode_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('podcastauthordynamics', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('podcastauthordynamics_author_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('podcastauthordynamics_other_author_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'podcastauthorpersona', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'podcastauthorpersona', ['other_author_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastauthordynamics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('podcastauthordynamics_other_author_id_fkey'), 'podcastauthorpersona', ['other_author_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('podcastauthordynamics_author_id_fkey'), 'podcastauthorpersona', ['author_id'], ['id'])

    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('conversation_episode_id_fkey'), 'podcastepisode', ['episode_id'], ['id'])

    # ### end Alembic commands ###
