"""Implement basic subscription

Revision ID: da5b74c8abd5
Revises: ce86322b1c93
Create Date: 2025-10-15 13:50:31.117949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'da5b74c8abd5'
down_revision: Union[str, None] = 'ce86322b1c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quota',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('quota_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptionplan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotaplanoverride',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscriptionplan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotaplanoverride')
    op.drop_table('subscriptionplan')
    op.drop_table('quota')
    # ### end Alembic commands ###
