"""Add recommendation system + like/dislike system

Revision ID: e25a9f873903
Revises: 6f1b242edd9b
Create Date: 2025-10-04 16:58:14.762014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e25a9f873903'
down_revision: Union[str, None] = '6f1b242edd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcastrecommendation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('podcast_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userlikehistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('podcast_id', sa.Uuid(), nullable=False),
    sa.Column('liked_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_like', sa.Boolean(), nullable=False),
    sa.Column('is_dislike', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['podcast_id'], ['podcast.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userprofile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userlikehistory')
    op.drop_table('podcastrecommendation')
    # ### end Alembic commands ###
