"""Make profile_id and audio_file NULLABLE

Revision ID: f364a86e5ebd
Revises: 6befde9ade9f
Create Date: 2025-06-16 14:37:39.799242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f364a86e5ebd'
down_revision: Union[str, None] = '6befde9ade9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.alter_column('profile_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.alter_column('audio_file',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('podcastepisode', schema=None) as batch_op:
        batch_op.alter_column('audio_file',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('podcast', schema=None) as batch_op:
        batch_op.alter_column('profile_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
